- hosts: all
  become: yes
  tasks:

  - name: add every machine to hosts file
    lineinfile:
      dest: /etc/hosts
      line: "{{ hostvars[item].ansible_host }}     {{ hostvars[item].inventory_hostname_short }}"
      state: present
    with_items: "{{ groups.all }}"

  - name: Install a list of packages
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest

  - name: Install Docker-Ce
    apt:
      pkg:
      - docker-ce={{ docker_version }}
      - docker-ce-cli={{ docker_version  }}

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: daemon.json
      dest: /etc/docker/daemon.json

  - name: create docker systemd directory
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory
      mode: 0750

  - name: Daemon-reload
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start and enable docker
    systemd:
     name: docker
     enabled: yes
     state: started

  - name: Disable swap permanently, persist reboots
    lineinfile:
      path: /etc/fstab
      regexp: '/swap.img'
      state: absent

  - name: add Kubernetes apt-key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: add Kubernetes' APT repository
    apt_repository:
     repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
     state: present
     filename: 'kubernetes'

  - name: install kubelet
    apt:
      name: kubelet={{ kubelet_version }}
      state: present

  - name: install kubeadm
    apt:
      name: kubeadm={{ kubeadm_version }}
      state: present

  - name: Letting iptables see bridged traffic
    sysctl:
     name: "{{ item.name }}"
     value: "{{ item.value }}"
     sysctl_file: /etc/sysctl.d/k8s.conf
    with_items:
    - name: net.bridge.bridge-nf-call-ip6tables
      value: '1'
    - name: net.bridge.bridge-nf-call-iptables
      value: '1'
    - name: net.ipv4.ip_forward
      value: '1'

  - name: Rebooting before initializing cluster
    reboot:
     msg: " rebooting after installing os and update"

- hosts: master
  become: yes
  tasks:

  - name: install kubectl
    apt:
      name: kubectl={{ kubectl_version }}
      state: present

  - name: initialize the cluster
    shell: kubeadm init
    args:
     chdir: $HOME
     creates: cluster_initialized.txt

  - name: create .kube directory
    become_user: "{{ ansible_user }}"
    file:
     path: ~/.kube
     state: directory
     mode: 0755

  - name: copy admin.conf to user's kube config
    become: yes
    copy:
     src: /etc/kubernetes/admin.conf
     dest: /home/{{ ansible_user }}/.kube/config
     remote_src: yes
     owner: "{{ ansible_user }}"

  - name: install Pod network
    become_user: "{{ ansible_user }}"
    shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
    args:
     chdir: $HOME
     creates: pod_network_setup.txt

  - name: get join command
    shell: kubeadm token create --print-join-command
    register: join_command_raw

  - name: set join command
    set_fact:
      join_command: "{{ join_command_raw.stdout_lines[0] }}"

  - name: Configure ufw rules for master
    ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }}
    with_items:
      - { rule: 'limit', port: '{{ ssh_port | default("22") }}', proto: 'tcp' }
      - { rule: 'allow', port: '6443', proto: 'tcp' }
      - { rule: 'allow', port: '2379', proto: 'tcp' }
      - { rule: 'allow', port: '2380', proto: 'tcp' }
      - { rule: 'allow', port: '10250', proto: 'tcp' }
      - { rule: 'allow', port: '10251', proto: 'tcp' }
      - { rule: 'allow', port: '10259', proto: 'tcp' }
      - { rule: 'allow', port: '10257', proto: 'tcp' }
      - { rule: 'allow', port: '6781', proto: 'tcp' }
      - { rule: 'allow', port: '6782', proto: 'tcp' }
      - { rule: 'allow', port: '6783', proto: 'tcp' }
      - { rule: 'allow', port: '6784', proto: 'tcp' }
      - { rule: 'allow', port: '6783', proto: 'udp' }
      - { rule: 'allow', port: '6784', proto: 'udp' }

  - name: Enabling UFW
    ufw:
      state: enabled      

- hosts: workers
  become: yes
  tasks:
  - name: join cluster
    shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
    args:
      chdir: $HOME
      creates: node_joined.txt

  - name: Configure ufw rules for workers
    ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }}
    with_items:
      - { rule: 'limit', port: '{{ ssh_port | default("22") }}', proto: 'tcp' }
      - { rule: 'allow', port: '30000:32767', proto: 'tcp' }
      - { rule: 'allow', port: '6781', proto: 'tcp' }
      - { rule: 'allow', port: '10250', proto: 'tcp' }
      - { rule: 'allow', port: '6782', proto: 'tcp' }
      - { rule: 'allow', port: '6783', proto: 'tcp' }
      - { rule: 'allow', port: '6784', proto: 'tcp' }
      - { rule: 'allow', port: '6783', proto: 'udp' }
      - { rule: 'allow', port: '6784', proto: 'udp' }    

  - name: Enabling UFW
    ufw:
      state: enabled
