- name: Reverting VM Snapshot
  hosts: localhost
  tasks:
  - name: Reverting Snapshots
    vmware_guest_snapshot:
     validate_certs: no
     hostname: YOUR VCENTER IP or FQDN
     username: YOUR VCENTER USER
     password: YOUR VCENTER USER PASSWORD
     datacenter: YOUR DATACENTER
     folder: FOLDER OF VIRTUAL MACHINE
     name: VIRTUAL MACHINE NAME
     state: revert
     snapshot_name: YOUR SNAPSHOT NAME
    delegate_to: localhost

  - name: Set the state of a virtual machine to power-on
    vmware_guest_powerstate:
      hostname: VCENTER-IP
      username: VCENTER-USERNAME
      password: PASSWORD
      validate_certs: no
      folder: FOLDER
      name: VMNAME
      state: powered-on
    delegate_to: localhost
    register: deploy


## You can copy and paste as many as you have virtual machines
