- hosts: all
  become: yes
  tasks:
  
  - name: Disabling swap
    ansible.builtin.lineinfile:
      path: /etc/fstab
      state: absent
      regexp: '/swap.img'

  - name: add every machine to hosts file
    lineinfile:
      dest: /etc/hosts
      line: "{{ hostvars[item].ansible_host }}     {{ hostvars[item].inventory_hostname_short }}"
      state: present
    with_items: "{{ groups.all }}"

  - name: Install a basic list of packages
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - net-tools

  - name: add Kubernetes apt-key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: add Kubernetes' APT repository
    apt_repository:
     repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
     state: present
     filename: 'kubernetes'

  - name: Yum update after os intallation
    yum:
     name: '*'
     state: latest
     update_cache: yes

  - name: Rebooting the machine
    reboot:
     msg: " rebooting after installing os and update"

  - name: Modifiying /etc/modules-load.d/containerd.conf
    ansible.builtin.lineinfile:
      path: /etc/modules-load.d/containerd.conf
      line: "{{ item }}"
      create: yes
    with_items:
    - overlay
    - br_netfilter

  - name: Create a directory for containerd
    ansible.builtin.file:
      path: /etc/containerd
      state: directory


  - name: Creating containerd config file
    ansible.builtin.file:
      path: /etc/containerd/config.toml
      state: touch

  - name: Add needed kernel modules without reloading
    modprobe:
      name: "{{ item }}"
    with_items:
      - overlay
      - br_netfilter

  - name: Modifiying /etc/sysctl.d/kubernetes.conf
    ansible.builtin.lineinfile:
      path: /etc/sysctl.d/kubernetes.conf
      line: "{{ item }}"
      create: yes
    with_items:
    - net.bridge.bridge-nf-call-ip6tables = 1
    - net.bridge.bridge-nf-call-iptables  = 1
    - net.ipv4.ip_forward                 = 1

  - name: restart sysctl
    shell: sysctl --system

  - name: Install Containerd
    apt:
      pkg:
      - containerd

  - name: Install kubeadm kubelet
    apt:
      pkg:
      - kubeadm={{ kubeadm_version }}
      - kubelet={{ kubelet_version }}

  - name: default to config
    shell: containerd config default > /etc/containerd/config.toml

  - name: Start and enable containerd
    systemd:
     name: containerd
     enabled: yes
     state: started

- hosts: master
  become: yes
  tasks:

  - name: install kubectl
    apt:
      name: kubectl={{ kubectl_version }}
      state: present

  - name: initialize the cluster
    shell: kubeadm init

  - name: create .kube directory
    become_user: "{{ ansible_user }}"
    file:
     path: ~/.kube
     state: directory
     mode: 0755    

  - name: copy admin.conf to user's kube config
    become: yes
    copy:
     src: /etc/kubernetes/admin.conf
     dest: /home/{{ ansible_user }}/.kube/config
     remote_src: yes
     owner: "{{ ansible_user }}"

  - name: get join command
    shell: kubeadm token create --print-join-command
    register: join_command_raw

  - name: set join command
    set_fact:
      join_command: "{{ join_command_raw.stdout_lines[0] }}"

  - name: install Pod network
    become_user: "{{ ansible_user }}"
    shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
    args:
     chdir: $HOME
     creates: pod_network_setup.txt

  - name: Configure ufw rules for master
    ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }}
    with_items:
      - { rule: 'limit', port: '{{ ssh_port | default("22") }}', proto: 'tcp' }
      - { rule: 'allow', port: '6443', proto: 'tcp' }
      - { rule: 'allow', port: '2379', proto: 'tcp' }
      - { rule: 'allow', port: '2380', proto: 'tcp' }
      - { rule: 'allow', port: '10250', proto: 'tcp' }
      - { rule: 'allow', port: '10251', proto: 'tcp' }
      - { rule: 'allow', port: '6781', proto: 'tcp' }
      - { rule: 'allow', port: '6782', proto: 'tcp' }
      - { rule: 'allow', port: '6783', proto: 'tcp' }
      - { rule: 'allow', port: '6784', proto: 'tcp' }
      - { rule: 'allow', port: '6783', proto: 'udp' }
      - { rule: 'allow', port: '6784', proto: 'udp' }

  - name: Enabling UFW
    ufw:
      state: enabled

- hosts: workers
  become: yes
  tasks:
  - name: join cluster
    shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
    args:
      chdir: $HOME
      creates: node_joined.txt

  - name: Configure ufw rules for workers
    ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }}
    with_items:
      - { rule: 'limit', port: '{{ ssh_port | default("22") }}', proto: 'tcp' }
      - { rule: 'allow', port: '30000:32767', proto: 'tcp' }
      - { rule: 'allow', port: '6781', proto: 'tcp' }
      - { rule: 'allow', port: '6782', proto: 'tcp' }
      - { rule: 'allow', port: '6783', proto: 'tcp' }
      - { rule: 'allow', port: '6784', proto: 'tcp' }
      - { rule: 'allow', port: '6783', proto: 'udp' }
      - { rule: 'allow', port: '6784', proto: 'udp' }    

  - name: Enabling UFW
    ufw:
      state: enabled   
